// SPDX-License-Identifier: MIT
#nullable enable

using BepInEx;
using SkipDropshipCompany.Core.Ports;
using SkipDropshipCompany.Core.Validation;
using SkipDropshipCompany.Interop;
using SkipDropshipCompany.Interop.Game.Patches;

namespace SkipDropshipCompany;

// MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Keep the
// entrypoint metadata and startup log tied to that generated plugin identity.
[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
[BepInProcess("Lethal Company.exe")]
public class SkipDropshipCompany : BaseUnityPlugin
{
    private static PluginController? controller;

    internal static PluginController Controller => controller!;

    private void Awake()
    {
        var logger = new BepInExPluginLogger(base.Logger);
        var config = BepInExPluginConfig.Bind(Config);
        var validationLogging = Config.Bind(
            "Debug",
            "ValidationLogging",
            false,
            "Enable structured validation logs for release validation and troubleshooting."
        );
        IValidationLogger validationLogger = validationLogging.Value
            ? new BepInExValidationLogger(logger, System.DateTime.UtcNow)
            : DisabledValidationLogger.Instance;

        validationLogger.Record(
            ValidationLogRecord.PluginLoaded(
                version: MyPluginInfo.PLUGIN_VERSION,
                validationLogging: validationLogging.Value,
                enabled: config.Enabled,
                requireReroutingOnFirstDay: config.RequireReroutingOnFirstDay
            )
        );

        controller = PluginController.Create(
            config: config,
            logger: logger,
            validationLogger: validationLogger
        );

        HarmonyPatchInstaller.Install();

        logger.LogInfo($"Plugin {MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} is loaded!");
    }
}
