// SPDX-License-Identifier: MIT
#nullable enable

using HarmonyLib;

namespace SkipDropshipCompany.Interop.Game.Patches;

internal static class HarmonyPatchInstaller
{
    // MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Use it
    // here so the Harmony ID always matches the BepInEx plugin GUID.
    private static readonly Harmony harmony = new(MyPluginInfo.PLUGIN_GUID);

    public static void Install()
    {
        // PatchAll(Assembly) keeps the scan target explicit while this patch
        // boundary owns Harmony setup.
        harmony.PatchAll(typeof(HarmonyPatchInstaller).Assembly);
    }
}
